export const MOCK_CATEGORIES = [
  { id: 1, name: 'Consoles', slug: 'consoles', image: '/images/nobg/consoles.png', position: 1 },
  { id: 2, name: 'Controllers', slug: 'controllers', image: '/images/nobg/controllers.png', position: 2 },
  { id: 3, name: 'Headsets', slug: 'headsets', image: '/images/nobg/headsets.png', position: 3 },
  { id: 4, name: 'Keyboards', slug: 'keyboards', image: '/images/nobg/keyboards.png', position: 4 },
  { id: 5, name: 'Mice', slug: 'mice', image: '/images/nobg/mice-detail.png', position: 5 },
  { id: 6, name: 'Monitors', slug: 'monitors', image: '/images/nobg/monitors.png', position: 6 },
  { id: 7, name: 'Games', slug: 'games', image: '/images/nobg/games.png', position: 7 },
  { id: 8, name: 'Accessories', slug: 'accessories', image: '/images/nobg/accessories.png', position: 8 }
];

export const MOCK_PRODUCTS = [
  {
    id: 1,
    slug: 'playstation-5-slim',
    name: 'PlayStation 5 Slim',
    brand: 'Sony',
    category: 'consoles',
    price: 499.99,
    original_price: null,
    image: '/images/nobg/consoles.png',
    gallery: ['/images/nobg/consoles.png', '/images/consoles.webp'],
    tagline: 'Ultra-high speed SSD with ray tracing and 4K gaming ready.',
    description: 'Experience lightning fast loading with an ultra-high speed SSD, deeper immersion with support for haptic feedback, adaptive triggers, and 3D Audio.',
    specs: {
      'Storage': '1TB NVMe SSD',
      'Resolution': 'Up to 4K 120Hz',
      'HDR': 'Supported',
      'Dimensions': '358 × 96 × 216 mm'
    },
    condition: 'Brand New',
    stock: 14,
    featured: true,
    badge: 'Flagship',
    seller: 'GameCraft Official'
  },
  {
    id: 2,
    slug: 'dualsense-wireless-controller',
    name: 'DualSense Wireless Controller',
    brand: 'Sony',
    category: 'controllers',
    price: 69.99,
    original_price: 74.99,
    image: '/images/nobg/controllers.png',
    gallery: ['/images/nobg/controllers.png', '/images/hero-controller.webp'],
    tagline: 'Haptic feedback, dynamic adaptive triggers, and built-in mic.',
    description: 'Discover a deeper, highly immersive gaming experience that brings the action to life in the palms of your hands.',
    specs: {
      'Connectivity': 'Bluetooth 5.1 / USB-C',
      'Battery Life': 'Up to 12 Hours',
      'Feedback': 'Dual Actuators Haptics',
      'Weight': '280g'
    },
    condition: 'Brand New',
    stock: 35,
    featured: true,
    badge: 'Popular',
    seller: 'GameCraft Official'
  },
  {
    id: 3,
    slug: 'razer-blackshark-v2-pro',
    name: 'Razer BlackShark V2 Pro',
    brand: 'Razer',
    category: 'headsets',
    price: 179.99,
    original_price: 199.99,
    image: '/images/nobg/headsets.png',
    gallery: ['/images/nobg/headsets.png', '/images/headsets.webp'],
    tagline: 'Wireless esports headset with ultra-clear microphone.',
    description: 'If esports is your calling, answer it with the ultimate wireless headset for competitive play, designed with top esports pros.',
    specs: {
      'Drivers': 'TriForce Titanium 50mm',
      'Microphone': 'HyperClear Supercardioid',
      'Battery': 'Up to 70 Hours',
      'Weight': '320g'
    },
    condition: 'Brand New',
    stock: 22,
    featured: true,
    badge: 'Deal',
    seller: 'Razer Store'
  },
  {
    id: 4,
    slug: 'nexus-charging-station',
    name: 'NEXUS Charging Station',
    brand: 'GameCraft',
    category: 'accessories',
    price: 29.99,
    original_price: 39.99,
    image: '/images/nobg/accessories.png',
    gallery: ['/images/nobg/accessories.png', '/images/accessories.webp'],
    tagline: 'Dual controller fast dock with intelligent charge management.',
    description: 'Click-in design charges up to two wireless controllers simultaneously without having to connect them to your console.',
    specs: {
      'Charging Ports': 'Dual Magnetic Dock',
      'Input': 'USB-C Fast Charging',
      'LED Indicators': 'Dual Status Glow',
      'Protection': 'Overcharge & Surge Guard'
    },
    condition: 'Brand New',
    stock: 50,
    featured: true,
    badge: 'Best Value',
    seller: 'GameCraft Official'
  },
  {
    id: 5,
    slug: 'apex-pro-tkl-keyboard',
    name: 'Apex Pro TKL Mechanical Keyboard',
    brand: 'SteelSeries',
    category: 'keyboards',
    price: 189.99,
    original_price: null,
    image: '/images/nobg/keyboards.png',
    gallery: ['/images/nobg/keyboards.png', '/images/keyboards.webp'],
    tagline: 'OmniPoint 2.0 adjustable hypermagnetic switches.',
    description: 'World fastest keyboard with customizable actuation points from 0.1mm to 4.0mm and rapid trigger capability.',
    specs: {
      'Switches': 'OmniPoint 2.0 Adjustable',
      'Layout': 'Tenkeyless (TKL)',
      'OLED Screen': 'Smart Display',
      'Frame': 'Aircraft Grade Aluminum'
    },
    condition: 'Brand New',
    stock: 18,
    featured: false,
    badge: 'Pro Tier',
    seller: 'SteelSeries Authorized'
  },
  {
    id: 6,
    slug: 'deathadder-v3-pro-mouse',
    name: 'DeathAdder V3 Pro Wireless Mouse',
    brand: 'Razer',
    category: 'mice',
    price: 149.99,
    original_price: null,
    image: '/images/nobg/mice-detail.png',
    gallery: ['/images/nobg/mice-detail.png', '/images/mice.webp'],
    tagline: '63g ultra-lightweight ergonomic esports mouse.',
    description: 'Refined in collaboration with top esports pros, iconic ergonomic form is now 25% lighter with next-gen sensor tech.',
    specs: {
      'Sensor': 'Focus Pro 30K Optical',
      'Max DPI': '30,000 DPI',
      'Weight': '63g Ultra-lightweight',
      'Battery': 'Up to 90 Hours'
    },
    condition: 'Brand New',
    stock: 29,
    featured: false,
    badge: null,
    seller: 'Razer Store'
  },
  {
    id: 7,
    slug: 'rog-swift-oled-34-monitor',
    name: 'ROG Swift OLED 34" Gaming Monitor',
    brand: 'ASUS',
    category: 'monitors',
    price: 899.99,
    original_price: 999.99,
    image: '/images/nobg/monitors.png',
    gallery: ['/images/nobg/monitors.png', '/images/monitors.webp'],
    tagline: 'Ultrawide 240Hz 0.03ms QD-OLED curved display.',
    description: 'Immerse in breathtaking clarity with 800R curved QD-OLED panel, true 10-bit color, and custom heatsink cooling.',
    specs: {
      'Panel': '34" QD-OLED Curved (800R)',
      'Refresh Rate': '240Hz',
      'Response Time': '0.03ms (GtG)',
      'Resolution': '3440 × 1440 WQHD'
    },
    condition: 'Brand New',
    stock: 8,
    featured: false,
    badge: 'Ultrawide',
    seller: 'ASUS ROG'
  },
  {
    id: 8,
    slug: 'elden-ring-shadow-of-the-erdtree',
    name: 'Elden Ring: Shadow of the Erdtree Edition',
    brand: 'FromSoftware',
    category: 'games',
    price: 79.99,
    original_price: null,
    image: '/images/nobg/games.png',
    gallery: ['/images/nobg/games.png', '/images/games.webp'],
    tagline: 'Includes base game and massive expansion chapter.',
    description: 'Guided by Empyrean Miquella, players are summoned to the Land of Shadow, a place obscured by the Erdtree where the goddess Marika first set foot.',
    specs: {
      'Platform': 'PS5 / Cross-Gen',
      'Genre': 'Action RPG',
      'Publisher': 'Bandai Namco',
      'Format': 'Physical Disc Edition'
    },
    condition: 'Brand New',
    stock: 40,
    featured: false,
    badge: 'GOTY Edition',
    seller: 'Bandai Namco Store'
  }
];
